spring.application.name=CodeColabServer

# Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d7bumbh4tr6s73bbjim0-a:5432/cocode_112s?sslmode=require
spring.datasource.username=cocode_user
spring.datasource.password=7NIDTLdYFNX1TXYmXPW1XanhqDVd11mh
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


# JWT
codecollab.app.jwtSecret=${JWT_SECRET}
codecollab.app.jwtExpirationMs=86400000

# Port
server.port=${PORT:8080}